# Generated by Django 3.0.2 on 2020-02-09 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20200209_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='assigner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_assigner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='assigner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
