# Generated by Django 3.0.2 on 2020-02-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200216_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='projects.Dict_ProjectStatus', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='projects.Dict_ProjectType', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dict_projectstatus',
            name='name_lang',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='dict_projecttype',
            name='name_lang',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Перевод'),
        ),
    ]
