# Generated by Django 3.0.2 on 2020-02-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200216_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dict_projectstatus',
            options={'ordering': ('sort',), 'verbose_name': 'Статус проекта', 'verbose_name_plural': 'Статусы проекта'},
        ),
        migrations.AlterModelOptions(
            name='dict_projecttype',
            options={'ordering': ('sort',), 'verbose_name': 'Тип проекта', 'verbose_name_plural': 'Типы проекта'},
        ),
        migrations.AddField(
            model_name='dict_projectstatus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='dict_projecttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
