# Generated by Django 3.0.2 on 2020-02-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200216_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_type', to='projects.Dict_CompanyType', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='projects.Dict_TaskStatus', verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='projects.Dict_TaskType', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
