# Generated by Django 3.0.2 on 2020-02-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_up',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='resultcompany_up', to='projects.Company', verbose_name='Головная организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_up',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='resultproject_up', to='projects.Project', verbose_name='Родительский проект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_up',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='resulttask_up', to='projects.Task', verbose_name='Родительская задача'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultcompany', to='projects.Company', verbose_name='Компания'),
        ),
    ]
