# Generated by Django 3.0.2 on 2020-02-23 16:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200220_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_children', to='projects.Company', verbose_name='Головная организация'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_children', to='projects.Project', verbose_name='Проект верхнего уровня'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_children', to='projects.Task', verbose_name='Задача верхнего уровня'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultproject', to='projects.Project', verbose_name='Проект'),
        ),
    ]
