# Generated by Django 3.0.2 on 2020-02-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200223_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resultproject', to='projects.Project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
