# Generated by Django 3.0.2 on 2020-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200223_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_CompanyStructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип в оргструктуре',
                'verbose_name_plural': 'Типы в оргструктуре',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Dict_ProjectStructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип в иерархии',
                'verbose_name_plural': 'Типы в иерархии',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Dict_TaskStructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип в оргструктуре',
                'verbose_name_plural': 'Типы в оргструктуре',
                'ordering': ('sort',),
            },
        ),
        migrations.AlterField(
            model_name='dict_companytype',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='dict_companytype',
            name='name_lang',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='dict_projectstatus',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='dict_projectstatus',
            name='name_lang',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='dict_projecttype',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='dict_projecttype',
            name='name_lang',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='dict_taskstatus',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='dict_taskstatus',
            name='name_lang',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='dict_tasktype',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='dict_tasktype',
            name='name_lang',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод'),
        ),
    ]
