# Generated by Django 3.0.2 on 2020-02-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200225_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dict_companytype',
            options={'ordering': ('sort',), 'verbose_name': 'Тип организации', 'verbose_name_plural': 'Типы организаций'},
        ),
        migrations.AlterModelOptions(
            name='dict_projectstatus',
            options={'ordering': ('sort',), 'verbose_name': 'Статус проекта', 'verbose_name_plural': 'Статусы проектов'},
        ),
        migrations.AlterModelOptions(
            name='dict_projectstructuretype',
            options={'ordering': ('sort',), 'verbose_name': 'Тип проектов в иерархии', 'verbose_name_plural': 'Типы проектов в иерархии'},
        ),
        migrations.AlterModelOptions(
            name='dict_projecttype',
            options={'ordering': ('sort',), 'verbose_name': 'Тип проекта', 'verbose_name_plural': 'Типы проектов'},
        ),
        migrations.AlterModelOptions(
            name='dict_taskstatus',
            options={'ordering': ('sort',), 'verbose_name': 'Статус задачи', 'verbose_name_plural': 'Статусы задач'},
        ),
        migrations.AlterModelOptions(
            name='dict_taskstructuretype',
            options={'ordering': ('sort',), 'verbose_name': 'Тип задачи в иерархии', 'verbose_name_plural': 'Типы задач в иерархии'},
        ),
        migrations.AlterModelOptions(
            name='dict_tasktype',
            options={'ordering': ('sort',), 'verbose_name': 'Тип задачи', 'verbose_name_plural': 'Типы задач'},
        ),
        migrations.AddField(
            model_name='company',
            name='structure_type',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_structure_type', to='projects.Dict_CompanyStructureType', verbose_name='Тип в оргструктуре'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='structure_type',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_structure_type', to='projects.Dict_ProjectStructureType', verbose_name='Тип проекта в иерархии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='structure_type',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='task_structure_type', to='projects.Dict_TaskStructureType', verbose_name='Тип задачи в иерархии'),
            preserve_default=False,
        ),
    ]
