# Generated by Django 3.0.3 on 2020-02-29 17:26

# import ckeditor_uploader.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200229_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Описание"),
        ),
    ]
