# Generated by Django 3.0.4 on 2020-03-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0022_auto_20200229_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultcompany', to='companies.Company', verbose_name='Компания'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Dict_CompanyStructureType',
        ),
        migrations.DeleteModel(
            name='Dict_CompanyType',
        ),
    ]
