# Generated by Django 3.0.4 on 2020-03-18 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0023_auto_20200313_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dateclose',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыт'),
        ),
        migrations.AddField(
            model_name='task',
            name='dateclose',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.CreateModel(
            name='ProjectTaskStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtype', models.CharField(choices=[('P', 'Project'), ('T', 'Task')], max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('description', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultprojectlog', to='projects.Project', verbose_name='Проект')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_status_log', to='projects.Dict_TaskStatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'История Проекта',
                'verbose_name_plural': 'Истории Проектов',
                'ordering': ('project', 'date'),
                'unique_together': {('project', 'status', 'date', 'author')},
            },
        ),
    ]
