# Generated by Django 3.0.4 on 2020-03-20 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0024_auto_20200318_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.CharField(max_length=1024, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultprojectlog', to='projects.Project', verbose_name='Проект')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_status_log', to='projects.Dict_ProjectStatus', verbose_name='Статус Проекта')),
            ],
            options={
                'verbose_name': 'История Проекта',
                'verbose_name_plural': 'Истории Проектов',
                'ordering': ('project', 'date'),
                'unique_together': {('project', 'status', 'date', 'author')},
            },
        ),
        migrations.CreateModel(
            name='TaskStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.CharField(max_length=1024, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='task_status_log', to='projects.Dict_TaskStatus', verbose_name='Статус Задачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resulttasklog', to='projects.Task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'История Задачи',
                'verbose_name_plural': 'Истории Задач',
                'ordering': ('task', 'date'),
                'unique_together': {('task', 'status', 'date', 'author')},
            },
        ),
        migrations.DeleteModel(
            name='ProjectTaskStatusLog',
        ),
    ]
