# Generated by Django 3.0.5 on 2020-04-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20200428_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент выполнения'),
        ),
    ]
