# Generated by Django 3.0.5 on 2020-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20200518_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент выполнения'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Время работы, час.'),
        ),
    ]
