# Generated by Django 3.0.5 on 2020-05-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financies', '0002_auto_20200526_2051'),
        ('projects', '0033_auto_20200518_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resultcurrency', to='financies.Dict_Currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
