# Generated by Django 3.0.5 on 2020-05-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_project_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
    ]
