# Generated by Django 3.0.5 on 2020-05-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200527_1402'),
        ('projects', '0035_remove_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resultcurrency', to='finance.Dict_Currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
