# Generated by Django 3.1.5 on 2021-02-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='historyjson',
            field=models.TextField(default=1, verbose_name='история'),
            preserve_default=False,
        ),
    ]
