# Generated by Django 3.1.5 on 2021-02-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_project_historyjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='historyjson',
        ),
    ]
