# Generated by Django 3.1.5 on 2021-02-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_remove_project_historyjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='structure_type',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_structure_type', to='projects.dict_projectstructuretype', verbose_name='Тип в иерархии'),
        ),
    ]
