# Generated by Django 3.1.5 on 2021-02-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20210212_1344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskstatuslog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskstatuslog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='taskstatuslog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskstatuslog',
            name='task',
        ),
        migrations.DeleteModel(
            name='ProjectStatusLog',
        ),
        migrations.DeleteModel(
            name='TaskStatusLog',
        ),
    ]
