# Generated by Django 3.1.5 on 2021-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20210216_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
