# Generated by Django 3.1.5 on 2021-03-31 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0044_auto_20210330_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='docfile',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_file', to='projects.project', verbose_name='Проект'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
