# Generated by Django 3.1.5 on 2021-03-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20210331_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='pfile',
            field=models.FileField(blank=True, null=True, upload_to='project', verbose_name='Файл'),
        ),
    ]
