# Generated by Django 3.1.5 on 2021-04-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20210331_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='pfile',
            field=models.FileField(blank=True, null=True, upload_to='upload/docs/project', verbose_name='Файл'),
        ),
    ]
