# Generated by Django 3.1.5 on 2021-04-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20210402_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='psize',
            field=models.CharField(default=100, editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
