# Generated by Django 3.1.5 on 2021-04-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_projectfile_psize'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_file', to='projects.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='taskcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskcomment_file', to='projects.taskcomment', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_file', to='projects.project', verbose_name='Проект'),
        ),
    ]
