# Generated by Django 3.1.5 on 2021-07-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20210414_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='pfile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files/projects', verbose_name='Файл'),
        ),
    ]
