# Generated by Django 4.1.7 on 2024-01-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0054_auto_20210714_1355"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_projectstatus",
            options={
                "verbose_name": "Статус проекта",
                "verbose_name_plural": "Статусы проектов",
            },
        ),
        migrations.RemoveField(
            model_name="dict_projectstatus",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_projectstatus",
            name="name_lang",
        ),
        migrations.AddField(
            model_name="dict_projectstatus",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_projectstatus",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_projectstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_projectstatus",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
    ]
