# Generated by Django 4.1.7 on 2024-01-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0055_alter_dict_projectstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dict_projectstatus",
            name="name_en",
            field=models.CharField(
                blank=True, default=2, max_length=64, verbose_name="Наименование_en"
            ),
            preserve_default=False,
        ),
    ]
