# Generated by Django 4.1.7 on 2024-01-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0056_alter_dict_projectstatus_name_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dict_projectstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
    ]
