# Generated by Django 4.1.7 on 2024-01-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0057_alter_dict_projectstatus_name_en"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_projectstructuretype",
            options={
                "verbose_name": "Тип проектов в иерархии",
                "verbose_name_plural": "Типы проектов в иерархии",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_projecttype",
            options={
                "verbose_name": "Тип проекта",
                "verbose_name_plural": "Типы проектов",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_taskstatus",
            options={
                "verbose_name": "Статус задачи",
                "verbose_name_plural": "Статусы задач",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_taskstructuretype",
            options={
                "verbose_name": "Тип задачи в иерархии",
                "verbose_name_plural": "Типы задач в иерархии",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_tasktype",
            options={"verbose_name": "Тип задачи", "verbose_name_plural": "Типы задач"},
        ),
        migrations.RemoveField(
            model_name="dict_projectstructuretype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_projectstructuretype",
            name="name_lang",
        ),
        migrations.RemoveField(
            model_name="dict_projecttype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_projecttype",
            name="name_lang",
        ),
        migrations.RemoveField(
            model_name="dict_taskstatus",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_taskstatus",
            name="name_lang",
        ),
        migrations.RemoveField(
            model_name="dict_taskstructuretype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_taskstructuretype",
            name="name_lang",
        ),
        migrations.RemoveField(
            model_name="dict_tasktype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_tasktype",
            name="name_lang",
        ),
        migrations.AddField(
            model_name="dict_projectstructuretype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_projectstructuretype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_projectstructuretype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_projectstructuretype",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dict_projecttype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_projecttype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_projecttype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_projecttype",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dict_taskstatus",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_taskstatus",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_taskstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_taskstatus",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dict_taskstructuretype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_taskstructuretype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_taskstructuretype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_taskstructuretype",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dict_tasktype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_tasktype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_tasktype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_tasktype",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
    ]
