# Generated by Django 4.1.7 on 2024-01-30 11:31

# import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0058_alter_dict_projectstructuretype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
    ]
