# Generated by Django 4.1.7 on 2024-01-30 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0059_alter_task_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_projectstatus",
            options={
                "ordering": ("sort",),
                "verbose_name": "Статус проекта",
                "verbose_name_plural": "Статусы проектов",
            },
        ),
    ]
