# Generated by Django 4.1.7 on 2024-01-30 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0060_alter_dict_projectstatus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_projectstatus",
            options={
                "verbose_name": "Статус проекта",
                "verbose_name_plural": "Статусы проектов",
            },
        ),
    ]
