# Generated by Django 4.1.7 on 2024-01-30 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0061_alter_dict_projectstatus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_projectstatus",
            options={
                "ordering": ["sort"],
                "verbose_name": "Статус проекта",
                "verbose_name_plural": "Статусы проектов",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_projectstructuretype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип проектов в иерархии",
                "verbose_name_plural": "Типы проектов в иерархии",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_projecttype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип проекта",
                "verbose_name_plural": "Типы проектов",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_taskstatus",
            options={
                "ordering": ["sort"],
                "verbose_name": "Статус задачи",
                "verbose_name_plural": "Статусы задач",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_taskstructuretype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип задачи в иерархии",
                "verbose_name_plural": "Типы задач в иерархии",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_tasktype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип задачи",
                "verbose_name_plural": "Типы задач",
            },
        ),
        migrations.AlterModelOptions(
            name="taskcomment",
            options={},
        ),
    ]
