# Generated by Django 4.1.7 on 2024-01-30 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0062_alter_dict_projectstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskcomment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
