# Generated by Django 4.1.7 on 2024-01-31 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0063_alter_taskcomment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["tree_id", "level", "dateend"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["tree_id", "level", "dateend"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
