# Generated by Django 3.0.5 on 2020-05-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200527_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencyrate_currency', to='finance.Dict_Currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'История курса валют',
                'verbose_name_plural': 'Истории курсов валют',
                'ordering': ('currency', 'date'),
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
