# Generated by Django 3.0.6 on 2020-05-29 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_currencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
    ]
