# Generated by Django 4.1.7 on 2023-03-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20200618_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_currency',
            name='name',
            field=models.CharField(help_text='Наименование валюты', max_length=64, verbose_name='Наименование'),
        ),
    ]
