# Generated by Django 4.1.7 on 2023-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_dict_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict_currency',
            name='name_en',
            field=models.CharField(help_text='Наименование валюты', max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='dict_currency',
            name='name_ru',
            field=models.CharField(help_text='Наименование валюты', max_length=64, null=True, verbose_name='Наименование'),
        ),
    ]
