# Generated by Django 4.1.7 on 2023-03-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_dict_currency_name_en_dict_currency_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict_currency',
            name='name_lang',
        ),
    ]
