# Generated by Django 4.1.7 on 2023-04-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_dict_currency_name_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict_currency',
            name='name',
        ),
        migrations.AlterField(
            model_name='dict_currency',
            name='name_en',
            field=models.CharField(default=1, help_text='Наименование валюты', max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dict_currency',
            name='name_ru',
            field=models.CharField(default=1, help_text='Наименование валюты', max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
    ]
