# Generated by Django 4.1.7 on 2023-04-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_dict_currency_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict_currency',
            name='shortname',
        ),
        migrations.AddField(
            model_name='dict_currency',
            name='shortname_en',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Краткое наименование_en'),
        ),
        migrations.AddField(
            model_name='dict_currency',
            name='shortname_ru',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Краткое наименование_ru'),
        ),
    ]
