# Generated by Django 4.1.7 on 2024-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0011_remove_dict_currency_shortname_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_currency",
            options={"verbose_name": "Вид валюты", "verbose_name_plural": "Виды валют"},
        ),
        migrations.AddField(
            model_name="dict_currency",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_currency",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AlterField(
            model_name="dict_currency",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_currency",
            name="name_ru",
            field=models.CharField(max_length=64, verbose_name="Наименование_ru"),
        ),
    ]
