# Generated by Django 3.1.5 on 2021-07-15 14:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0033_auto_20200724_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_FeedbackTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_close', models.BooleanField(default=False, verbose_name='Закрывает задачу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Dict_FeedbackTicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_close', models.BooleanField(default=False, verbose_name='Закрывает тикет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус тикета',
                'verbose_name_plural': 'Статусы тикетов',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Dict_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='Код системы')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование системы')),
                ('domain', models.CharField(blank=True, max_length=64, null=True, verbose_name='Наименование домена')),
                ('url', models.CharField(max_length=128, verbose_name='url')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='ip-адрес')),
                ('email', models.CharField(blank=True, max_length=15, null=True, verbose_name='Контактный e-mail')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Контактный телефон')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=128, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системы',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('datebegin', models.DateTimeField(verbose_name='Начало')),
                ('dateend', models.DateTimeField(verbose_name='Окончание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент выполнения')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('dateclose', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_task_assigner', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_task_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_children', to='feedback.feedbacktask', verbose_name='Задача верхнего уровня')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_taskstatus', to='feedback.dict_feedbacktaskstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('dateclose', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_ticket_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_company', to='companies.company', verbose_name='Компания')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_ticketstatus', to='feedback.dict_feedbackticketstatus', verbose_name='Статус')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_system', to='feedback.dict_system', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
            },
        ),
        migrations.CreateModel(
            name='FeedbackTicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('time', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Время работы, час.')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_ticket', to='feedback.feedbackticket', verbose_name='Тикет')),
            ],
            options={
                'verbose_name': 'Комментарий тикета',
                'verbose_name_plural': 'Комментарии тикетов',
            },
        ),
        migrations.CreateModel(
            name='FeedbackTaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('time', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Время работы, час.')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resulttask', to='feedback.feedbacktask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарий задачи',
                'verbose_name_plural': 'Комментарии задач',
            },
        ),
        migrations.AddField(
            model_name='feedbacktask',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultticket', to='feedback.feedbackticket', verbose_name='Тикет'),
        ),
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('uname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникальное наименование')),
                ('pfile', models.FileField(blank=True, null=True, upload_to='uploads/files/feedback', verbose_name='Файл')),
                ('psize', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacktask_file', to='feedback.feedbacktask', verbose_name='Задача')),
                ('taskcomment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacktaskcomment_file', to='feedback.feedbacktaskcomment', verbose_name='Комментарий задачи')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackticket_file', to='feedback.feedbackticket', verbose_name='Тикет')),
                ('ticketcomment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketcomment_file', to='feedback.feedbackticketcomment', verbose_name='Комментарий тикета')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
