# Generated by Django 3.1.5 on 2021-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_system',
            name='code',
            field=models.CharField(editable=False, max_length=128, verbose_name='Код системы'),
        ),
    ]
