# Generated by Django 3.1.5 on 2021-07-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_dict_feedbacktickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackticket',
            name='type',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tickettype', to='feedback.dict_feedbacktickettype', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
