# Generated by Django 3.1.5 on 2021-09-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_company_is_support'),
        ('feedback', '0008_remove_feedbackticket_id_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackticket',
            name='companyfrom',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_companyfrom', to='companies.company', verbose_name='Компания автора'),
            preserve_default=False,
        ),
    ]
