# Generated by Django 3.1.5 on 2021-10-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_company_is_support'),
        ('feedback', '0009_feedbackticket_companyfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackticketcomment',
            name='company',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_commentcompany', to='companies.company', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
