# Generated by Django 3.1.5 on 2021-11-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_dict_system_requestcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dict_system',
            old_name='requestcode',
            new_name='requeststatuscode',
        ),
    ]
