# Generated by Django 3.1.5 on 2021-11-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_auto_20211105_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_system',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Контактный e-mail'),
        ),
    ]
