# Generated by Django 3.1.5 on 2021-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_auto_20211124_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict_system',
            name='is_local',
            field=models.BooleanField(default=True, verbose_name='Локальность'),
        ),
    ]
