# Generated by Django 3.1.5 on 2021-12-03 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_company_is_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0014_dict_system_is_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackticket',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_ticket_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_company', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='feedbackticket',
            name='companyfrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_companyfrom', to='companies.company', verbose_name='Компания автора'),
        ),
    ]
