# Generated by Django 3.1.5 on 2021-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_auto_20211203_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackticket',
            name='id_remote',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID тикета в удалённой системе'),
        ),
    ]
