# Generated by Django 3.1.5 on 2021-12-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_feedbackticket_id_remote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackticketcomment',
            old_name='company',
            new_name='companies',
        ),
    ]
