# Generated by Django 3.1.5 on 2021-12-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_company_is_support'),
        ('feedback', '0017_auto_20211210_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackticketcomment',
            name='companies',
        ),
        migrations.AddField(
            model_name='feedbackticketcomment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_commentcompany', to='companies.company', verbose_name='Компания'),
        ),
    ]
