# Generated by Django 3.1.5 on 2021-12-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_auto_20211223_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackticketcomment',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='feedbackticketcomment',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Время работы, час.'),
        ),
    ]
