# Generated by Django 3.1.5 on 2022-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_auto_20211226_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackticketcomment',
            name='id_remote',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID комментария в удалённой системе'),
        ),
    ]
