# Generated by Django 4.1.7 on 2024-01-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0022_feedbackticketcomment_id_remote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dict_feedbacktaskstatus",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_feedbacktaskstatus",
            name="name_lang",
        ),
        migrations.RemoveField(
            model_name="dict_feedbackticketstatus",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_feedbackticketstatus",
            name="name_lang",
        ),
        migrations.RemoveField(
            model_name="dict_feedbacktickettype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_feedbacktickettype",
            name="name_lang",
        ),
        migrations.AddField(
            model_name="dict_feedbacktaskstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_feedbacktaskstatus",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dict_feedbackticketstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_feedbackticketstatus",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dict_feedbacktickettype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_feedbacktickettype",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
    ]
