# Generated by Django 4.1.7 on 2024-01-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0024_alter_feedbacktask_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_feedbacktaskstatus",
            options={
                "verbose_name": "Статус задачи",
                "verbose_name_plural": "Статусы задач",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_feedbackticketstatus",
            options={
                "verbose_name": "Статус тикета",
                "verbose_name_plural": "Статусы тикетов",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_feedbacktickettype",
            options={
                "verbose_name": "Тип тикета",
                "verbose_name_plural": "Типы тикетов",
            },
        ),
        migrations.AddField(
            model_name="dict_feedbacktaskstatus",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_feedbacktaskstatus",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_feedbackticketstatus",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_feedbackticketstatus",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_feedbacktickettype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_feedbacktickettype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
    ]
