# Generated by Django 4.1.7 on 2024-01-30 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0025_alter_dict_feedbacktaskstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_feedbacktaskstatus",
            options={
                "ordering": ["sort"],
                "verbose_name": "Статус задачи",
                "verbose_name_plural": "Статусы задач",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_feedbackticketstatus",
            options={
                "ordering": ["sort"],
                "verbose_name": "Статус тикета",
                "verbose_name_plural": "Статусы тикетов",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_feedbacktickettype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип тикета",
                "verbose_name_plural": "Типы тикетов",
            },
        ),
    ]
