# Generated by Django 3.0.4 on 2020-03-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200321_1945'),
        ('accounts', '0002_auto_20200323_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_company_profile', to='companies.Company', verbose_name='Организация'),
        ),
    ]
