# Generated by Django 3.0.5 on 2020-04-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200418_1654'),
        ('accounts', '0003_auto_20200323_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_notify',
            field=models.BooleanField(default=True, verbose_name='Оповещать'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='protocoltype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_protocol_type', to='main.Dict_ProtocolType', verbose_name='Протокол оповещения'),
        ),
    ]
