# Generated by Django 3.1.5 on 2021-07-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_dict_theme'),
        ('accounts', '0005_auto_20200418_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='protocoltype',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='result_protocol_type', to='main.dict_protocoltype', verbose_name='Протокол оповещения'),
        ),
    ]
