# Generated by Django 4.1.7 on 2023-04-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Язык'),
        ),
    ]
