# Generated by Django 4.1.7 on 2023-04-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='Метка удаления'),
        ),
    ]
