# Generated by Django 4.1.7 on 2023-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_is_del'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_del',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Язык'),
        ),
    ]
