# Generated by Django 5.0.2 on 2024-02-15 07:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userprofile_is_del_alter_userprofile_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
