# Generated by Django 3.1.5 on 2021-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210428_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='datepublic',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
