# Generated by Django 3.1.5 on 2021-05-04 14:17

# import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0033_auto_20200724_1449'),
        ('docs', '0003_doc_datepublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='DocVer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('datepublic', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docver_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docver_company', to='companies.company', verbose_name='Организация')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docver_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер документа')),
                ('members', models.ManyToManyField(related_name='docver_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='docver_status', to='docs.dict_docstatus', verbose_name='Статус документа')),
                ('type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='docver_type', to='docs.dict_doctype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
            },
        ),
        migrations.AddField(
            model_name='docfile',
            name='docver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docver_file', to='docs.docver', verbose_name='Версия Документа'),
        ),
    ]
