# Generated by Django 3.1.5 on 2021-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_auto_20200724_1449'),
        ('docs', '0006_doctaskcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='docver',
            options={'verbose_name': 'Версия Документа', 'verbose_name_plural': 'Версии Документов'},
        ),
        migrations.AddField(
            model_name='docver',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальность'),
        ),
        migrations.AlterUniqueTogether(
            name='docver',
            unique_together={('company', 'is_actual')},
        ),
    ]
