# Generated by Django 3.1.5 on 2021-05-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20210505_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AlterUniqueTogether(
            name='docver',
            unique_together=set(),
        ),
    ]
