# Generated by Django 3.1.5 on 2021-05-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20210505_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='docver',
            name='doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='docver_doc', to='docs.doc', verbose_name='Документ'),
            preserve_default=False,
        ),
    ]
