# Generated by Django 3.1.5 on 2021-05-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_docver_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docver',
            name='company',
        ),
    ]
