# Generated by Django 3.1.5 on 2021-05-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_remove_docver_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='docver',
            name='vernumber',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер версии'),
            preserve_default=False,
        ),
    ]
