# Generated by Django 3.1.5 on 2021-05-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_docver_is_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docver',
            name='is_act',
        ),
    ]
