# Generated by Django 3.1.5 on 2021-05-07 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0014_remove_docver_is_act'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocVerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('uname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникальное наименование')),
                ('pfile', models.FileField(blank=True, null=True, upload_to='uploads/files/docs/doc/<django.db.models.fields.related.ForeignKey>', verbose_name='Файл')),
                ('psize', models.CharField(editable=False, max_length=64)),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_file', to='docs.doc', verbose_name='Документ')),
                ('docver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docver_file', to='docs.docver', verbose_name='Версия Документа')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.DeleteModel(
            name='DocFile',
        ),
    ]
