# Generated by Django 3.1.5 on 2021-05-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_auto_20210507_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docverfile',
            name='pfile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files/docs/doc', verbose_name='Файл'),
        ),
    ]
