# Generated by Django 3.1.5 on 2021-05-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0017_docver_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docver',
            name='company',
        ),
    ]
