# Generated by Django 3.1.5 on 2021-06-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0018_remove_docver_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='docverfile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctask_file', to='docs.doctask', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='docverfile',
            name='taskcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctaskcomment_file', to='docs.doctaskcomment', verbose_name='Комментарий'),
        ),
    ]
