# Generated by Django 3.1.5 on 2021-06-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0019_auto_20210609_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctaskcomment',
            name='name',
        ),
    ]
