# Generated by Django 3.1.5 on 2021-06-11 13:05

# import ckeditor_uploader.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0020_remove_doctaskcomment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dict_docstatus",
            name="is_close",
        ),
        migrations.AddField(
            model_name="dict_docstatus",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публикует документ"),
        ),
        migrations.AlterField(
            model_name="doctaskcomment",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Текст"),
        ),
    ]
