# Generated by Django 3.1.5 on 2021-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0021_auto_20210611_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_docstatus',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публикует версию документа'),
        ),
    ]
