# Generated by Django 3.1.5 on 2021-06-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0022_auto_20210617_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='is_public',
        ),
        migrations.AddField(
            model_name='docver',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Опубликована'),
        ),
    ]
