# Generated by Django 3.1.5 on 2021-07-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0023_auto_20210617_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docverfile',
            name='pfile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files/docs', verbose_name='Файл'),
        ),
    ]
