# Generated by Django 4.1.7 on 2024-01-29 15:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docs", "0026_remove_dict_docstatus_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctaskcomment",
            name="name",
            field=models.CharField(
                default=1, max_length=128, verbose_name="Наименование"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doctaskcomment",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Описание"
            ),
        ),
    ]
