# Generated by Django 4.1.7 on 2024-01-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docs", "0027_doctaskcomment_name_alter_doctaskcomment_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_docstatus",
            options={
                "verbose_name": "Статус документа",
                "verbose_name_plural": "Статусы документов",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_doctaskstatus",
            options={
                "verbose_name": "Статус задачи",
                "verbose_name_plural": "Статусы задач",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_doctasktype",
            options={"verbose_name": "Тип задачи", "verbose_name_plural": "Типы задач"},
        ),
        migrations.AlterModelOptions(
            name="dict_doctype",
            options={
                "verbose_name": "Тип документ",
                "verbose_name_plural": "Типы документов",
            },
        ),
        migrations.AlterField(
            model_name="dict_docstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_doctaskstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_doctasktype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_doctype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
    ]
