# Generated by Django 5.0.2 on 2024-02-15 07:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0030_alter_doctaskcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctaskcomment',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
    ]
