# Generated by Django 3.0.4 on 2020-03-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_component_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='sort',
        ),
    ]
