# Generated by Django 3.0.4 on 2020-03-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_component_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='menu',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Пункт меню'),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
    ]
