# Generated by Django 3.0.5 on 2020-04-18 13:45

# import ckeditor_uploader.fields
from django_ckeditor_5.fields import CKEditor5Field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20200321_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_ProtocolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Протокол оповещения',
                'verbose_name_plural': 'Протокол оповещений',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('sendfrom', models.CharField(blank=True, max_length=64, null=True, verbose_name='От кого')),
                ('theme', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тема')),
                ('text', CKEditor5Field(max_length=1024, verbose_name='Текст')),
                ('sendto', models.CharField(blank=True, max_length=64, null=True, verbose_name='Кому')),
                ('datesent', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='protocol_type', to='main.Dict_ProtocolType', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
    ]
