# Generated by Django 3.0.5 on 2020-05-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200519_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='dateкread',
            new_name='dateread',
        ),
    ]
