# Generated by Django 3.0.5 on 2020-05-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200519_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sendfromid',
        ),
    ]
