# Generated by Django 3.0.5 on 2020-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200519_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=8, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('tablename', models.CharField(max_length=64, verbose_name='Таблица')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Список объектов',
                'verbose_name_plural': 'Списки объектов',
                'ordering': ('sort',),
            },
        ),
    ]
