# Generated by Django 3.0.5 on 2020-05-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_meta_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object',
            field=models.ForeignKey(default=3, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='meta_object', to='main.Meta_Object', verbose_name='Объект'),
            preserve_default=False,
        ),
    ]
