# Generated by Django 3.0.5 on 2020-05-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_notification_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta_Object',
            new_name='Meta_ObjectType',
        ),
        migrations.AlterModelOptions(
            name='meta_objecttype',
            options={'ordering': ('sort',), 'verbose_name': 'Список типов объектов', 'verbose_name_plural': 'Списки типов объектов'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object',
        ),
        migrations.AddField(
            model_name='notification',
            name='objectid',
            field=models.PositiveIntegerField(default=0, verbose_name='ID объекта'),
        ),
        migrations.AddField(
            model_name='notification',
            name='objecttype',
            field=models.ForeignKey(default=3, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='meta_objecttype', to='main.Meta_ObjectType', verbose_name='Тип Объекта'),
            preserve_default=False,
        ),
    ]
