# Generated by Django 3.1.5 on 2021-03-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210212_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_service', models.BooleanField(default=True, verbose_name='Система, как сервис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность Системы')),
            ],
            options={
                'ordering': ('datecreate',),
            },
        ),
    ]
