# Generated by Django 3.1.5 on 2021-03-16 16:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_meta_param'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=64, verbose_name='slug')),
                ('base_url', models.CharField(max_length=128, verbose_name='Основной URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Список меню',
                'verbose_name_plural': 'Списки меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link_url', models.CharField(max_length=128, verbose_name='URL')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_component', to='main.component', verbose_name='Компонент')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_menu', to='main.menu', verbose_name='Меню')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_children', to='main.menuitem', verbose_name='Головная пункт меню')),
            ],
            options={
                'verbose_name': 'Пункты меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ('menu', 'sort'),
            },
        ),
    ]
