# Generated by Django 3.1.5 on 2021-04-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210316_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Пункты меню', 'verbose_name_plural': 'Пункты меню'},
        ),
    ]
