# Generated by Django 3.1.5 on 2021-06-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210428_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_objecttype',
            name='shortname',
            field=models.CharField(max_length=16, verbose_name='Код'),
        ),
    ]
