# Generated by Django 3.1.5 on 2021-06-30 11:55

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210609_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_children', to='main.dict_theme', verbose_name='Головная тематика')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематика',
            },
        ),
    ]
