# Generated by Django 4.1.7 on 2023-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220204_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(default=models.CharField(max_length=128, verbose_name='Наименование'), max_length=128, verbose_name='Наименование_en'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_ru',
            field=models.CharField(default=models.CharField(max_length=128, verbose_name='Наименование'), max_length=128, verbose_name='Наименование_ru'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, default=15, null=True),
        ),
    ]
