# Generated by Django 4.1.7 on 2023-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_menuitem_description_en_menuitem_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(default='title', max_length=128, verbose_name='Наименование_en'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title_ru',
            field=models.CharField(default='title', max_length=128, verbose_name='Наименование_ru'),
        ),
    ]
