# Generated by Django 4.1.7 on 2023-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_menuitem_title_alter_menuitem_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.AddField(
            model_name='menu',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_en',
            field=models.CharField(default=1, max_length=128, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
