# Generated by Django 4.1.7 on 2023-04-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_description_menu_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание_en'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание_ru'),
        ),
    ]
