# Generated by Django 4.1.7 on 2023-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_menu_description_en_alter_menu_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='menu',
            new_name='menu_ru',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='dict_protocoltype',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='dict_theme',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='dict_theme',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='meta_objecttype',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='meta_param',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RemoveField(
            model_name='dict_protocoltype',
            name='name_lang',
        ),
        migrations.RemoveField(
            model_name='meta_objecttype',
            name='name_lang',
        ),
        migrations.AddField(
            model_name='component',
            name='description_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='component',
            name='menu_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Пункт меню'),
        ),
        migrations.AddField(
            model_name='component',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='dict_protocoltype',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='dict_theme',
            name='description_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='dict_theme',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='meta_objecttype',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='meta_param',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='dict_protocoltype',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Наименование_en'),
        ),
        migrations.AlterField(
            model_name='meta_objecttype',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Сортировка'),
        ),
    ]
