# Generated by Django 4.1.7 on 2023-04-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_description_component_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Наименование'),
        ),
    ]
