# Generated by Django 4.1.7 on 2023-04-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_component_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='name',
        ),
    ]
