# Generated by Django 4.1.7 on 2023-12-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_component_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_client_default',
            field=models.BooleanField(default=False, verbose_name='Подключать клиенту по-умолчанию'),
        ),
        migrations.AddField(
            model_name='component',
            name='is_employee_default',
            field=models.BooleanField(default=False, verbose_name='Подключать сотруднику по-умолчанию'),
        ),
    ]
