# Generated by Django 4.1.7 on 2023-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_component_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read_isauthor',
            field=models.BooleanField(default=False, verbose_name='Прочитано исходящее'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read_isrecipient',
            field=models.BooleanField(default=False, verbose_name='Прочитано входящее'),
        ),
    ]
