# Generated by Django 4.1.7 on 2024-01-24 15:59

from django.db import migrations, models
import main.utils_lang


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_remove_notification_is_read_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dict_Model",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=64, verbose_name="Наименование_ru"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Наименование_en",
                    ),
                ),
                (
                    "sort",
                    models.PositiveSmallIntegerField(blank=True, default=1, null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
            ],
            bases=(main.utils_lang.TranslateFieldMixin, models.Model),
        ),
    ]
