# Generated by Django 4.1.7 on 2024-01-24 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_dict_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dict_Model",
        ),
    ]
