# Generated by Django 4.1.7 on 2024-01-29 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0038_comment_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment_Model",
        ),
    ]
