# Generated by Django 4.1.7 on 2024-01-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_delete_comment_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meta_objecttype",
            options={
                "verbose_name": "Список типов объектов",
                "verbose_name_plural": "Списки типов объектов",
            },
        ),
        migrations.AddField(
            model_name="meta_objecttype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="meta_objecttype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AlterField(
            model_name="meta_objecttype",
            name="sort",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
