# Generated by Django 4.1.7 on 2024-01-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0040_alter_meta_objecttype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_protocoltype",
            options={
                "verbose_name": "Протокол оповещения",
                "verbose_name_plural": "Протоколы оповещений",
            },
        ),
        migrations.AddField(
            model_name="dict_protocoltype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_protocoltype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_theme",
            name="sort",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="dict_protocoltype",
            name="sort",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="dict_theme",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AlterField(
            model_name="dict_theme",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
    ]
