# Generated by Django 4.1.7 on 2024-02-01 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0041_alter_dict_protocoltype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meta_objecttype",
            options={
                "ordering": ("sort",),
                "verbose_name": "Список типов объектов",
                "verbose_name_plural": "Списки типов объектов",
            },
        ),
    ]
