# Generated by Django 5.0.2 on 2024-02-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_meta_objecttype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='Текст'),
        ),
    ]
