# Generated by Django 3.0.4 on 2020-03-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200314_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompany',
            options={'ordering': ('user', 'company'), 'verbose_name': 'Пользователь Организации', 'verbose_name_plural': 'Пользователи Организаций'},
        ),
    ]
