# Generated by Django 3.0.4 on 2020-04-06 17:45

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0005_auto_20200321_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип контента',
                'verbose_name_plural': 'Типы контента',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Заголовок')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('datebegin', models.DateField(verbose_name='Начало')),
                ('dateend', models.DateField(verbose_name='Окончание')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_company', to='companies.Company', verbose_name='Организация')),
                ('type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='companies.Dict_ContentType', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ('company', 'type', 'datecreate'),
            },
        ),
    ]
