# Generated by Django 3.0.4 on 2020-04-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20200406_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='announcement',
            field=models.TextField(default=1, max_length=10240, verbose_name='Анонс'),
            preserve_default=False,
        ),
    ]
