# Generated by Django 3.0.4 on 2020-04-08 16:12

# import ckeditor_uploader.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_content_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ("datecreate", "datebegin", "dateend", "type"),
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
        migrations.AlterField(
            model_name="content",
            name="announcement",
            field=models.TextField(
                blank=True, max_length=10240, null=True, verbose_name="Анонс"
            ),
        ),
        migrations.RemoveField(
            model_name="content",
            name="company",
        ),
        migrations.AddField(
            model_name="content",
            name="company",
            field=models.ManyToManyField(
                related_name="content_companies",
                to="companies.Company",
                verbose_name="Организации",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
    ]
