# Generated by Django 3.0.5 on 2020-04-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20200408_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('-is_ontop', '-id'), 'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AddField(
            model_name='content',
            name='is_ontop',
            field=models.BooleanField(default=False, verbose_name='Всегда наверху'),
        ),
    ]
