# Generated by Django 3.0.5 on 2020-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20200410_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Только для внешнего сайта'),
        ),
    ]
