# Generated by Django 3.0.5 on 2020-05-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_dict_contentplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='place',
            field=models.ForeignKey(default=2, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='content_place', to='companies.Dict_ContentPlace', verbose_name='Место'),
            preserve_default=False,
        ),
    ]
