# Generated by Django 3.0.5 on 2020-05-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_content_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_forprofile',
        ),
        migrations.RemoveField(
            model_name='content',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='content',
            name='is_public',
        ),
    ]
