# Generated by Django 3.0.5 on 2020-05-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200527_1402'),
        ('companies', '0015_auto_20200506_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_currency', to='finance.Dict_Currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
