# Generated by Django 3.0.6 on 2020-06-18 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_auto_20200618_1813'),
        ('companies', '0016_company_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип должности',
                'verbose_name_plural': 'Типы должностей',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Оклад')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('company', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='related_company', to='companies.Company', verbose_name='Организация')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_currency', to='finance.Dict_Currency', verbose_name='Валюта')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_children', to='companies.Staff', verbose_name='Головная должность')),
                ('type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='position_type', to='companies.Dict_PositionType', verbose_name='Тип должности')),
            ],
            options={
                'verbose_name': 'Штатное расписание',
                'verbose_name_plural': 'Штатные расписания',
            },
        ),
    ]
