# Generated by Django 3.0.6 on 2020-06-19 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0019_auto_20200618_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datebegin', models.DateTimeField(auto_now_add=True, verbose_name='Начало работы')),
                ('dateend', models.DateTimeField(auto_now_add=True, verbose_name='Окончание работы')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('stafflist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_stafflist', to='companies.StaffList', verbose_name='Должность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('stafflist', 'user'),
                'unique_together': {('stafflist', 'user')},
            },
        ),
    ]
