# Generated by Django 3.0.6 on 2020-07-08 13:26

# import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name="stafflist",
            name="is_vacancy",
            field=models.BooleanField(default=False, verbose_name="Вакансия"),
        ),
        migrations.AddField(
            model_name="stafflist",
            name="vacancy",
            field=models.TextField(default=1, verbose_name="Описание вакансии"),
            preserve_default=False,
        ),
    ]
