# Generated by Django 3.0.6 on 2020-07-08 13:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_auto_20200708_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflist',
            name='vacancy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание вакансии'),
        ),
    ]
