# Generated by Django 3.0.6 on 2020-07-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_auto_20200708_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='datebegin',
            field=models.DateField(auto_now_add=True, verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dateend',
            field=models.DateField(auto_now_add=True, verbose_name='Окончание работы'),
        ),
    ]
