# Generated by Django 3.0.6 on 2020-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_auto_20200713_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='datebegin',
            field=models.DateField(verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dateend',
            field=models.DateField(verbose_name='Окончание работы'),
        ),
    ]
