# Generated by Django 3.0.6 on 2020-07-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_auto_20200716_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Ставка (0,1 - 1)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='stafflist',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_stafflist', to='companies.StaffList', verbose_name='Должность'),
        ),
    ]
