# Generated by Django 3.0.6 on 2020-07-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_auto_20200716_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set(),
        ),
    ]
