# Generated by Django 3.0.6 on 2020-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_auto_20200716_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflist',
            name='numberemployees',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во сотрудников'),
        ),
    ]
