# Generated by Django 3.0.6 on 2020-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_auto_20200722_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='candidatemiddlename',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='email',
            field=models.CharField(default=1, max_length=64, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summary',
            name='phone',
            field=models.CharField(default=1, max_length=16, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
