# Generated by Django 3.0.6 on 2020-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_auto_20200723_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон'),
        ),
    ]
