# Generated by Django 3.0.6 on 2020-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_auto_20200724_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='email',
            field=models.CharField(default=1, max_length=64, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summary',
            name='phone',
            field=models.CharField(default=2, max_length=16, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
