# Generated by Django 3.1.5 on 2021-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_auto_20200724_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_support',
            field=models.BooleanField(default=False, verbose_name='Служба техподдержки'),
        ),
    ]
