# Generated by Django 3.1.5 on 2021-03-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0033_auto_20200724_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='groups',
            field=models.ManyToManyField(related_name='company_groups', to='auth.Group', verbose_name='Группы'),
        ),
    ]
