# Generated by Django 4.1.7 on 2024-01-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0035_remove_dict_companystructuretype_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_companystructuretype",
            options={
                "verbose_name": "Тип в оргструктуре",
                "verbose_name_plural": "Типы в оргструктуре",
            },
        ),
        migrations.AddField(
            model_name="dict_companystructuretype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_companystructuretype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AlterField(
            model_name="dict_companystructuretype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
    ]
