# Generated by Django 4.1.7 on 2024-01-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0036_alter_dict_companystructuretype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_companytype",
            options={
                "verbose_name": "Тип организации",
                "verbose_name_plural": "Типы организаций",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_contentplace",
            options={
                "verbose_name": "Место отображения контента",
                "verbose_name_plural": "Места отображения контента",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_contenttype",
            options={
                "verbose_name": "Тип контента",
                "verbose_name_plural": "Типы контента",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_positiontype",
            options={
                "verbose_name": "Тип должности",
                "verbose_name_plural": "Типы должностей",
            },
        ),
        migrations.AddField(
            model_name="dict_companytype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_companytype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_contentplace",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_contentplace",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_contenttype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_contenttype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_positiontype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_positiontype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AlterField(
            model_name="dict_companytype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_contentplace",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_contentplace",
            name="sort",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="dict_contenttype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_positiontype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
    ]
