# Generated by Django 4.1.7 on 2024-01-30 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0037_alter_dict_companytype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_companystructuretype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип в оргструктуре",
                "verbose_name_plural": "Типы в оргструктуре",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_companytype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип организации",
                "verbose_name_plural": "Типы организаций",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_contentplace",
            options={
                "ordering": ["sort"],
                "verbose_name": "Место отображения контента",
                "verbose_name_plural": "Места отображения контента",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_contenttype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип контента",
                "verbose_name_plural": "Типы контента",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_positiontype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип должности",
                "verbose_name_plural": "Типы должностей",
            },
        ),
    ]
