# Generated by Django 4.1.7 on 2024-02-01 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0038_alter_dict_companystructuretype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["tree_id", "level"],
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
    ]
