# Generated by Django 5.0.2 on 2024-02-12 10:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_alter_content_announcement_alter_content_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='announcement',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=10240, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст'),
        ),
    ]
