# Generated by Django 5.0.2 on 2024-02-12 12:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_alter_content_announcement_alter_content_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
