# Generated by Django 5.0.2 on 2024-02-15 07:32

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0043_alter_summary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stafflist',
            name='vacancy',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание вакансии'),
        ),
    ]
