# Generated by Django 3.0.6 on 2021-01-12 09:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0033_auto_20200724_1449'),
        ('main', '0014_auto_20200523_1915'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_ClientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус клиента',
                'verbose_name_plural': 'Статусы клиентов',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Dict_ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип клиента',
                'verbose_name_plural': 'Типы клиентов',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notify', models.BooleanField(default=False, verbose_name='Оповещать')),
                ('firstname', models.CharField(max_length=64, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('lastname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('dateclose', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_company_client', to='companies.Company', verbose_name='Организация')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_manager_client', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('members', models.ManyToManyField(related_name='client_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('protocoltype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_protocoltype_client', to='main.Dict_ProtocolType', verbose_name='Протокол оповещения')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='client_status_client', to='crm.Dict_ClientStatus', verbose_name='Статус клиента')),
                ('type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='client_type_client', to='crm.Dict_ClientType', verbose_name='Тип клиента')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_user_client', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль Клиента',
                'verbose_name_plural': 'Профили Клиентов',
            },
        ),
    ]
