# Generated by Django 3.0.6 on 2021-01-13 15:04

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_auto_20210112_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('datebegin', models.DateTimeField(verbose_name='Начало')),
                ('dateend', models.DateTimeField(verbose_name='Окончание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент выполнения')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('dateclose', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienttask_assigner', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultclienttaskuser', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultclient', to='crm.Client', verbose_name='Клиент')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_children', to='crm.ClientTask', verbose_name='Задача верхнего уровня')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Dict_ClientStructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип проектов в иерархии',
                'verbose_name_plural': 'Типы проектов в иерархии',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Dict_ClientTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_close', models.BooleanField(default=False, verbose_name='Закрывает задачу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Dict_ClientTaskStructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип задачи в иерархии',
                'verbose_name_plural': 'Типы задач в иерархии',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='Dict_ClientTaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='ClientTaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('time', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Время работы, час.')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultclienttask', to='crm.ClientTask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='clienttask',
            name='status',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clienttask_status', to='crm.Dict_ClientTaskStatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='structure_type',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clienttask_structure_type', to='crm.Dict_ClientTaskStructureType', verbose_name='Тип задачи в иерархии'),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='type',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clienttask_type', to='crm.Dict_ClientTaskType', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='ClientTaskStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.CharField(max_length=1024, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clienttask_status_log', to='crm.Dict_ClientTaskStatus', verbose_name='Статус Задачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultclienttasklog', to='crm.ClientTask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'История Задачи',
                'verbose_name_plural': 'Истории Задач',
                'ordering': ('task', 'date'),
                'unique_together': {('task', 'status', 'date', 'author')},
            },
        ),
        migrations.CreateModel(
            name='ClientStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.CharField(max_length=1024, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultclientlog', to='crm.Client', verbose_name='Проект')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='client_status_log', to='crm.Dict_ClientStatus', verbose_name='Статус Клиента')),
            ],
            options={
                'verbose_name': 'История Клиента',
                'verbose_name_plural': 'Истории Клиентов',
                'ordering': ('client', 'date'),
                'unique_together': {('client', 'status', 'date', 'author')},
            },
        ),
    ]
