# Generated by Django 3.0.6 on 2021-01-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210113_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dict_ClientStructureType',
        ),
    ]
