# Generated by Django 3.0.6 on 2021-01-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_delete_dict_clientstructuretype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_clientstatus',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Наименование'),
        ),
    ]
