# Generated by Django 3.0.6 on 2021-01-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20200618_1813'),
        ('crm', '0006_auto_20210113_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='result_currency_client', to='finance.Dict_Currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент выполнения'),
        ),
        migrations.AlterField(
            model_name='dict_clientstatus',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
    ]
