# Generated by Django 3.1.5 on 2021-01-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210115_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict_clientstatus',
            name='is_close',
            field=models.BooleanField(default=False, verbose_name='Закрывает клиента'),
        ),
    ]
