# Generated by Django 3.1.5 on 2021-01-25 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0008_dict_clientstatus_is_close'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientstatuslog',
            options={'ordering': ('client', 'dt'), 'verbose_name': 'История Клиента', 'verbose_name_plural': 'Истории Клиентов'},
        ),
        migrations.RenameField(
            model_name='clientstatuslog',
            old_name='date',
            new_name='dt',
        ),
        migrations.AlterUniqueTogether(
            name='clientstatuslog',
            unique_together={('client', 'status', 'dt', 'author')},
        ),
    ]
