# Generated by Django 3.1.5 on 2021-01-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20210125_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatuslog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultclientlog', to='crm.client', verbose_name='Клиент'),
        ),
    ]
