# Generated by Django 3.1.5 on 2021-01-25 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_auto_20210125_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienttaskstatuslog',
            options={'ordering': ('task', 'dt'), 'verbose_name': 'История Задачи', 'verbose_name_plural': 'Истории Задач'},
        ),
        migrations.RenameField(
            model_name='clienttaskstatuslog',
            old_name='date',
            new_name='dt',
        ),
        migrations.AlterUniqueTogether(
            name='clienttaskstatuslog',
            unique_together={('task', 'status', 'dt', 'author')},
        ),
    ]
