# Generated by Django 3.1.5 on 2021-01-25 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0011_auto_20210125_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientstatuslog',
            options={'ordering': ('client', 'date'), 'verbose_name': 'История Клиента', 'verbose_name_plural': 'Истории Клиентов'},
        ),
        migrations.AlterModelOptions(
            name='clienttaskstatuslog',
            options={'ordering': ('task', 'date'), 'verbose_name': 'История Задачи', 'verbose_name_plural': 'Истории Задач'},
        ),
        migrations.RenameField(
            model_name='clientstatuslog',
            old_name='dt',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='clienttaskstatuslog',
            old_name='dt',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='clientstatuslog',
            unique_together={('client', 'status', 'date', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='clienttaskstatuslog',
            unique_together={('task', 'status', 'date', 'author')},
        ),
    ]
