# Generated by Django 3.1.5 on 2021-01-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20210125_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_ClientInitiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Инициатор',
                'verbose_name_plural': 'Инициаторы',
                'ordering': ('sort',),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='initiator',
            field=models.CharField(choices=[('CLNT', 'Клиент'), ('ORG', 'Компания'), ('OTHER', 'Другое')], default=1, max_length=5, verbose_name='Инициатор'),
            preserve_default=False,
        ),
    ]
