# Generated by Django 3.1.5 on 2021-01-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_client_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='initiator',
            field=models.ForeignKey(default=2, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clienttask_initiator', to='crm.dict_clientinitiator', verbose_name='Инициатор задачи'),
            preserve_default=False,
        ),
    ]
