# Generated by Django 3.1.5 on 2021-02-02 10:27

# import ckeditor_uploader.fields

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_clienttask_initiator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_ClientEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
                'ordering': ('sort',),
            },
        ),
        migrations.AddField(
            model_name='clienttask',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='Это событие'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clienttask_type', to='crm.dict_clienttasktype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='typeevent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientevent_type', to='crm.dict_clienteventtype', verbose_name='Тип события'),
        ),
    ]
