# Generated by Django 3.1.5 on 2021-02-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20210202_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict_clienttaskstatus',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='initiator',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clienttask_initiator', to='crm.dict_clientinitiator', verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='structure_type',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clienttask_structure_type', to='crm.dict_clienttaskstructuretype', verbose_name='Тип в иерархии'),
        ),
    ]
