# Generated by Django 3.1.5 on 2021-02-02 15:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0018_auto_20210202_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('datebegin', models.DateTimeField(verbose_name='Начало')),
                ('dateend', models.DateTimeField(verbose_name='Окончание')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dateclose', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assigner', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_client', to='crm.client', verbose_name='Клиент')),
                ('initiator', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='event_initiator', to='crm.dict_clientinitiator', verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Dict_ClientEventStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name_lang', models.CharField(blank=True, max_length=64, null=True, verbose_name='Перевод')),
                ('is_close', models.BooleanField(default=False, verbose_name='Закрывает событие')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус события',
                'verbose_name_plural': 'Статусы событий',
                'ordering': ('sort',),
            },
        ),
        migrations.RemoveField(
            model_name='clienttask',
            name='is_event',
        ),
        migrations.RemoveField(
            model_name='dict_clienttaskstatus',
            name='is_event',
        ),
        migrations.CreateModel(
            name='ClientEventComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultclientevent', to='crm.clientevent', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='clientevent',
            name='status',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='event_status', to='crm.dict_clienteventstatus', verbose_name='Статус события'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='task',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventtask', to='crm.clienttask', verbose_name='Связанная задача'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_type', to='crm.dict_clienteventtype', verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='ClientEventStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.CharField(max_length=1024, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultclienteventlog', to='crm.clientevent', verbose_name='Событие')),
                ('status', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clientevent_status_log', to='crm.dict_clienteventstatus', verbose_name='Статус События')),
            ],
            options={
                'verbose_name': 'История События',
                'verbose_name_plural': 'Истории Событий',
                'ordering': ('event', 'date'),
                'unique_together': {('event', 'status', 'date', 'author')},
            },
        ),
    ]
