# Generated by Django 3.1.5 on 2021-02-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20210202_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientevent',
            name='place',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Место'),
        ),
    ]
