# Generated by Django 4.1.7 on 2023-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20210714_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict_clienteventstatus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dict_clienteventstatus',
            name='name_lang',
        ),
        migrations.RemoveField(
            model_name='dict_clienteventtype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dict_clienteventtype',
            name='name_lang',
        ),
        migrations.RemoveField(
            model_name='dict_clientinitiator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dict_clientinitiator',
            name='name_lang',
        ),
        migrations.RemoveField(
            model_name='dict_clientstatus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dict_clientstatus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dict_clientstatus',
            name='name_lang',
        ),
        migrations.RemoveField(
            model_name='dict_clienttaskstatus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dict_clienttaskstatus',
            name='name_lang',
        ),
        migrations.RemoveField(
            model_name='dict_clienttaskstructuretype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dict_clienttaskstructuretype',
            name='name_lang',
        ),
        migrations.RemoveField(
            model_name='dict_clienttasktype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dict_clienttasktype',
            name='name_lang',
        ),
        migrations.RemoveField(
            model_name='dict_clienttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dict_clienttype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dict_clienttype',
            name='name_lang',
        ),
        migrations.AddField(
            model_name='dict_clienteventstatus',
            name='name_en',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienteventstatus',
            name='name_ru',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienteventtype',
            name='name_en',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienteventtype',
            name='name_ru',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clientinitiator',
            name='name_en',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clientinitiator',
            name='name_ru',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clientstatus',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание_en'),
        ),
        migrations.AddField(
            model_name='dict_clientstatus',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание_ru'),
        ),
        migrations.AddField(
            model_name='dict_clientstatus',
            name='name_en',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clientstatus',
            name='name_ru',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienttaskstatus',
            name='name_en',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienttaskstatus',
            name='name_ru',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienttaskstructuretype',
            name='name_en',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienttaskstructuretype',
            name='name_ru',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienttasktype',
            name='name_en',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienttasktype',
            name='name_ru',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienttype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание_en'),
        ),
        migrations.AddField(
            model_name='dict_clienttype',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание_ru'),
        ),
        migrations.AddField(
            model_name='dict_clienttype',
            name='name_en',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_clienttype',
            name='name_ru',
            field=models.CharField(default=1, max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
    ]
