# Generated by Django 4.1.7 on 2024-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0026_remove_dict_clienteventstatus_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienteventcomment",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=9,
                null=True,
                verbose_name="Стоимость",
            ),
        ),
        migrations.AddField(
            model_name="clienteventcomment",
            name="time",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=6,
                null=True,
                verbose_name="Затраченное время, час.",
            ),
        ),
    ]
