# Generated by Django 4.1.7 on 2024-01-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0027_clienteventcomment_cost_clienteventcomment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clienttask",
            name="datecreate",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
        ),
    ]
