# Generated by Django 4.1.7 on 2024-01-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0028_alter_clienttask_datecreate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_clienteventstatus",
            options={
                "verbose_name": "Статус события",
                "verbose_name_plural": "Статусы событий",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clienteventtype",
            options={
                "verbose_name": "Тип события",
                "verbose_name_plural": "Типы событий",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clientinitiator",
            options={"verbose_name": "Инициатор", "verbose_name_plural": "Инициаторы"},
        ),
        migrations.AlterModelOptions(
            name="dict_clientstatus",
            options={
                "verbose_name": "Статус клиента",
                "verbose_name_plural": "Статусы клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clienttaskstatus",
            options={
                "verbose_name": "Статус задачи",
                "verbose_name_plural": "Статусы задач",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clienttaskstructuretype",
            options={
                "verbose_name": "Тип задачи в иерархии",
                "verbose_name_plural": "Типы задач в иерархии",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clienttasktype",
            options={"verbose_name": "Тип задачи", "verbose_name_plural": "Типы задач"},
        ),
        migrations.AlterModelOptions(
            name="dict_clienttype",
            options={
                "verbose_name": "Тип клиента",
                "verbose_name_plural": "Типы клиентов",
            },
        ),
        migrations.AddField(
            model_name="dict_clienteventstatus",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_clienteventstatus",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_clienteventtype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_clienteventtype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_clientinitiator",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_clientinitiator",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_clienttaskstatus",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_clienttaskstatus",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_clienttaskstructuretype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_clienttaskstructuretype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AddField(
            model_name="dict_clienttasktype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_clienttasktype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AlterField(
            model_name="dict_clienteventstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_clienteventtype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_clientinitiator",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_clientstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_clienttaskstatus",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_clienttaskstructuretype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_clienttasktype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_clienttype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
    ]
