# Generated by Django 4.1.7 on 2024-01-30 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0029_alter_dict_clienteventstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_clienteventstatus",
            options={
                "ordering": ["sort"],
                "verbose_name": "Статус события",
                "verbose_name_plural": "Статусы событий",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clienteventtype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип события",
                "verbose_name_plural": "Типы событий",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clientinitiator",
            options={
                "ordering": ["sort"],
                "verbose_name": "Инициатор",
                "verbose_name_plural": "Инициаторы",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clientstatus",
            options={
                "ordering": ["sort"],
                "verbose_name": "Статус клиента",
                "verbose_name_plural": "Статусы клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clienttaskstatus",
            options={
                "ordering": ["sort"],
                "verbose_name": "Статус задачи",
                "verbose_name_plural": "Статусы задач",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clienttaskstructuretype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип задачи в иерархии",
                "verbose_name_plural": "Типы задач в иерархии",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clienttasktype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип задачи",
                "verbose_name_plural": "Типы задач",
            },
        ),
        migrations.AlterModelOptions(
            name="dict_clienttype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип клиента",
                "verbose_name_plural": "Типы клиентов",
            },
        ),
    ]
