# Generated by Django 4.1.7 on 2024-01-30 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0030_alter_dict_clienteventstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clienteventcomment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="clienttaskcomment",
            options={},
        ),
    ]
