# Generated by Django 4.1.7 on 2024-01-31 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0032_alter_clienteventcomment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clienttask",
            options={
                "ordering": ["tree_id", "level", "dateend"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
