# Generated by Django 3.1.5 on 2022-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='dateonline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Момент последней активности'),
        ),
    ]
