# Generated by Django 3.1.5 on 2022-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatmember_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
