# Generated by Django 3.1.5 on 2022-02-03 09:53

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_auto_20220131_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='onlyfor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_message_onlyfor', to=settings.AUTH_USER_MODEL, verbose_name='Только для'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
