# Generated by Django 3.1.5 on 2022-04-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_chatmember_dateoffline'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='datecurrent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Момент последней активности'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='dateonline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Момент входа в чат'),
        ),
    ]
