# Generated by Django 4.1.7 on 2023-12-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20220414_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict_chattype',
            name='name',
        ),
        migrations.AddField(
            model_name='dict_chattype',
            name='name_en',
            field=models.CharField(default='Приватный', max_length=64, verbose_name='Наименование_en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dict_chattype',
            name='name_ru',
            field=models.CharField(default=5, max_length=64, verbose_name='Наименование_ru'),
            preserve_default=False,
        ),
    ]
