# Generated by Django 4.1.7 on 2023-12-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_remove_dict_chattype_name_dict_chattype_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict_chattype',
            name='name_lang',
        ),
    ]
