# Generated by Django 4.1.7 on 2024-01-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0009_remove_dict_chattype_name_lang"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_chattype",
            options={"verbose_name": "Тип чата", "verbose_name_plural": "Типы чатов"},
        ),
        migrations.AddField(
            model_name="dict_chattype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_chattype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
        migrations.AlterField(
            model_name="dict_chattype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
    ]
