# Generated by Django 4.1.7 on 2024-01-30 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0010_alter_dict_chattype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_chattype",
            options={
                "ordering": ["sort"],
                "verbose_name": "Тип чата",
                "verbose_name_plural": "Типы чатов",
            },
        ),
    ]
