# Generated by Django 5.0.2 on 2024-02-15 07:31

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_alter_dict_chattype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
    ]
