# Generated by Django 3.1.5 on 2021-07-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_auto_20200724_1449'),
        ('files', '0002_auto_20210630_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_company_folder', to='companies.company', verbose_name='Компания'),
        ),
    ]
