# Generated by Django 3.1.5 on 2021-07-08 11:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210701_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
