# Generated by Django 3.1.5 on 2021-07-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20210714_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderfile',
            name='psize',
        ),
    ]
