# Generated by Django 3.1.5 on 2021-07-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_folderfile_psize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folderfile',
            old_name='size',
            new_name='psize',
        ),
    ]
