# Generated by Django 4.1.7 on 2024-01-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0008_auto_20210714_1351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dict_foldertype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="dict_foldertype",
            name="name_lang",
        ),
        migrations.AddField(
            model_name="dict_foldertype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AddField(
            model_name="dict_foldertype",
            name="name_ru",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Наименование_ru"
            ),
            preserve_default=False,
        ),
    ]
