# Generated by Django 4.1.7 on 2024-01-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0009_remove_dict_foldertype_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_foldertype",
            options={
                "verbose_name": "Тип содержимого папки",
                "verbose_name_plural": "Типы содержимого папок",
            },
        ),
        migrations.AddField(
            model_name="dict_foldertype",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_en"),
        ),
        migrations.AddField(
            model_name="dict_foldertype",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание_ru"),
        ),
    ]
