# Generated by Django 4.1.7 on 2024-01-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0011_alter_dict_foldertype_name_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dict_foldertype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
    ]
