# Generated by Django 5.0.2 on 2024-02-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_dict_foldertype_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
