# Generated by Django 4.1.7 on 2023-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=128, verbose_name='Наименование')),
                ('name_en', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание_ru')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание_en')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность Системы')),
            ],
        ),
    ]
