# Generated by Django 4.1.7 on 2023-05-03 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utils_lang


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0034_company_is_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict_ListFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=128, verbose_name='Наименование_ru')),
                ('name_en', models.CharField(max_length=128, verbose_name='Наименование_en')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание_ru')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание_en')),
                ('sort', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип данных',
                'verbose_name_plural': 'Типы данных',
                'ordering': ('sort',),
            },
            bases=(main.utils_lang.TranslateFieldMixin, models.Model),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('fieldslist', models.CharField(max_length=1024, verbose_name='Список и тип полей')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dateupdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('dateclose', models.DateTimeField(auto_now_add=True, verbose_name='Дата закрытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность Списка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('authorupdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_author_update', to=settings.AUTH_USER_MODEL, verbose_name='Автор последних изменений')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listresultcompany', to='companies.company', verbose_name='Компания')),
                ('members', models.ManyToManyField(related_name='list_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
        ),
    ]
