# Generated by Django 4.1.7 on 2023-11-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ylistitem',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
