# Generated by Django 4.1.7 on 2024-01-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dict_ylistfieldtype",
            options={
                "verbose_name": "Тип данных",
                "verbose_name_plural": "Типы данных",
            },
        ),
        migrations.AlterField(
            model_name="dict_ylistfieldtype",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Наименование_en"
            ),
        ),
        migrations.AlterField(
            model_name="dict_ylistfieldtype",
            name="name_ru",
            field=models.CharField(max_length=64, verbose_name="Наименование_ru"),
        ),
        migrations.AlterField(
            model_name="dict_ylistfieldtype",
            name="sort",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
