# Generated by Django 4.1.7 on 2023-05-03 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldslist', models.TextField(blank=True, null=True, verbose_name='Список и значения полей')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dateupdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('dateclose', models.DateTimeField(auto_now_add=True, verbose_name='Дата закрытия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность элемента Списка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listitem_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('authorupdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listitem_author_update', to=settings.AUTH_USER_MODEL, verbose_name='Автор последних изменений')),
                ('listlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listresult', to='lists.list', verbose_name='Список')),
            ],
        ),
    ]
