# Generated by Django 4.1.7 on 2023-05-03 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_company_is_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_listitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dict_ListFieldType',
            new_name='Dict_YListFieldType',
        ),
        migrations.RenameModel(
            old_name='List',
            new_name='YList',
        ),
        migrations.RenameModel(
            old_name='ListItem',
            new_name='YListItem',
        ),
        migrations.RenameField(
            model_name='ylistitem',
            old_name='listlist',
            new_name='ylist',
        ),
    ]
