# Generated by Django 4.1.7 on 2023-05-04 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_company_is_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0004_alter_ylist_dateclose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ylist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ylist_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='ylist',
            name='authorupdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ylist_author_update', to=settings.AUTH_USER_MODEL, verbose_name='Автор последних изменений'),
        ),
        migrations.AlterField(
            model_name='ylist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ylistresultcompany', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='ylist',
            name='members',
            field=models.ManyToManyField(related_name='ylist_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='ylistitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ylistitem_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='ylistitem',
            name='authorupdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ylistitem_author_update', to=settings.AUTH_USER_MODEL, verbose_name='Автор последних изменений'),
        ),
        migrations.AlterField(
            model_name='ylistitem',
            name='ylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ylistresult', to='lists.ylist', verbose_name='Список'),
        ),
    ]
