# Generated by Django 4.1.7 on 2023-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_alter_ylist_author_alter_ylist_authorupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ylistitem',
            name='dateclose',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
