# Generated by Django 4.1.7 on 2023-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_ylistitem_dateclose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ylist',
            options={'verbose_name': 'Список', 'verbose_name_plural': 'Списки'},
        ),
        migrations.AlterModelOptions(
            name='ylistitem',
            options={'ordering': ('sort',), 'verbose_name': 'Запись списка', 'verbose_name_plural': 'Записи списков'},
        ),
        migrations.AddField(
            model_name='ylistitem',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
