# Generated by Django 4.1.7 on 2023-11-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_alter_ylist_options_alter_ylistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ylistitem',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True),
        ),
    ]
