# Generated by Django 3.0.5 on 2020-05-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict_currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Символ'),
        ),
        migrations.AlterField(
            model_name='dict_currency',
            name='shortname',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Краткое наименование'),
        ),
    ]
